name: Publish addon

on:
  push:
    tags:
      - '*'
      - '!*-beta'

jobs:
  build-frontend-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build JS Bundle
        run: |
          cd frontend
          npm run build
          cd $GITHUB_WORKSPACE

      - name: Generate checksums
        run: |
          cd script.module.web-pdb/libs/web_pdb/static
          echo "SHA256 hashes for minified files:"
          sha256sum bundle.min.js | tee bundle.min.js.sha256
          sha256sum styles.min.css | tee styles.min.css.sha256
          cd $GITHUB_WORKSPACE
          git config user.name "$GITHUB_REPOSITORY_OWNER"
          git config user.email "roman1972@gmail.com"
          git add .
          git commit -m "Add compiled static files"

  publish:
    needs:
      - build-frontend-assets

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
    - name: Check with addon-checker
      run: |
        kodi-addon-checker --branch matrix script.module.web-pdb
    - name: Install addon submitter
      run: |
        pip install -q git+https://github.com/xbmc/kodi-addon-submitter.git
    - name: Submit addon
      run: |
        submit-addon -r repo-scrapers -b matrix -s --pull-request script.module.web-pdb
      env:
        GH_USERNAME: romanvm
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        EMAIL: roman1972@gmail.com
